error: can't copy 'init_db.py': doesn't exist or not a regular file
